DROP TABLE IF EXISTS polls CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS options CASCADE;
DROP TABLE IF EXISTS users_choices CASCADE;


CREATE TABLE users (
	id SERIAL PRIMARY KEY NOT NULL,
	email VARCHAR(50) NOT NULL,
	name VARCHAR(50) NOT NULL
);

CREATE TABLE polls (
	id SERIAL PRIMARY KEY NOT NULL,
	question VARCHAR(100),
	type INTEGER NOT NULL,
	creator_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE options (
	id SERIAL PRIMARY KEY NOT NULL,
	description VARCHAR(150) NOT NULL,
	poll_id INTEGER REFERENCES polls(id) ON DELETE CASCADE
);

CREATE TABLE users_choices (
	user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
	option_id INTEGER REFERENCES options(id) ON DELETE CASCADE,
	PRIMARY KEY(user_id, option_id),
	rank INTEGER NOT NULL
);




SELECT polls.question, options.description
FROM polls
JOIN options ON polls.id = options.poll_id
WHERE polls.id = 1;